### ISSUE TITLE
How to know input matrix to complete?

### ISSUE THREAD

**Issue by JasOlean** [tonyduan/matrix-completion#1]
I would like to know how can I decide the input matrix to complete before using matrix-completion?

**Comment by tonyduan** [comment]
Typically this is decided with domain knowledge.

For example, when predicting movie recommendations the matrix can represent users along one axis and movies along another. We make incomplete observations of the matrix (only a subset of movies are rated by each user), and use completion to predict ratings for unseen movies.

This paper is fairly accessible: https://papers.nips.cc/paper/3208-probabilistic-matrix-factorization.pdf.

**Comment by JasOlean** [comment]
In my case, I have missing joints for pose estimation.
I want to recover these joints using matrix completion.
So, do you think could I use these methods to recover missing joints for pose?
For the mask, how to define that?

**Comment by tonyduan** [comment]
Unfortunately, I don't have much domain expertise in pose estimation, so I'm not quite sure if matrix estimation is the best way to frame the problem.

The mask is a matrix of the same shape as the matrix you're trying to complete, with entries 1 (indicating observed) or 0 (indicating missing).
